baseurl = "https://fantastic-channel.surge.sh/"
title = "Canopy Tech"
languageCode = "en-us"
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme="casper"
disqusShortname = "canopy-tech"

[params]
cover = "images/cover.png"
# description = "Engineering at Canopy"
